# Generated by Django 3.1.1 on 2023-04-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstaff',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
