# Generated by Django 3.1.1 on 2023-05-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_notificationstaff_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstudent',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
